Manually merged updates from the old debian branch

diff --git a/debian/freeradius-mysql.postinst b/debian/freeradius-mysql.postinst
--- a/debian/freeradius-mysql.postinst
+++ b/debian/freeradius-mysql.postinst
@@ -5,9 +5,11 @@ set -e
 case "$1" in
   configure)
         if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-          invoke-rc.d freeradius force-reload
+          # Customized by Painless Security: Don't abort install if the reload fails
+          invoke-rc.d freeradius force-reload || true
         else
-          /etc/init.d/freeradius force-reload
+          # Customized by Painless Security: Don't abort install if the reload fails
+          /etc/init.d/freeradius force-reload || true
         fi
 	;;
 esac
